import { Colors, UserTypeProps } from "../../common/models/UserType";
import { Coin } from "../../common/models/Coin";
import { TimeFrame } from "../../common/models/Vote";
import { Leader } from "../../Contexts/CoinsContext";
import { User } from "firebase/auth";

export const pages = [
  {
    title: "x",
    content:
      '\n<h2>VOTE, MINT, EARN CRYPTO &amp; NFT</h2>\n\n\n\n<p style="font-size:17px">Make better investment decisions with the world’s first social indicator</p>\n',
    slug: "home",
  },
  {
    title: "About",
    content:
      "\n<p>You might be an artist who would like to introduce yourself and your work here or maybe you&rsquo;re a business with a mission to describe.</p>\n",
    slug: "about",
  },
  {
    title: "-",
    content:
      '\n<p>Voting Parliament © 2022 | Block 98, 1PAX = 10USD</p>\n\n\n\n<p>Total vote = 10,000 </p>\n\n\n\n<p><a href="https://coin-parliament.com/about/" data-type="page" data-id="6">About</a>. <a href="https://coin-parliament.com/faq/" data-type="page" data-id="54">FAQ</a>. <a href="https://coin-parliament.com/contact/" data-type="page" data-id="56">Contact</a>. <a href="https://coin-parliament.com/privacy/" data-type="page" data-id="3">Privacy</a>.</p>\n',
    slug: "footer",
  },
  {
    title: "-",
    content: "",
    slug: "contact",
  },
  {
    title: "-",
    content: "",
    slug: "faq",
  },
  {
    title: "-",
    content:
      '<h2>Who we are</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Our website address is: http://coin-parliament.com.</p><h2>Comments</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>When visitors leave comments on the site we collect the data shown in the comments form, and also the visitor&#8217;s IP address and browser user agent string to help spam detection.</p><p>An anonymized string created from your email address (also called a hash) may be provided to the Gravatar service to see if you are using it. The Gravatar service privacy policy is available here: https://automattic.com/privacy/. After approval of your comment, your profile picture is visible to the public in the context of your comment.</p><h2>Media</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you upload images to the website, you should avoid uploading images with embedded location data (EXIF GPS) included. Visitors to the website can download and extract any location data from images on the website.</p><h2>Cookies</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you leave a comment on our site you may opt-in to saving your name, email address and website in cookies. These are for your convenience so that you do not have to fill in your details again when you leave another comment. These cookies will last for one year.</p><p>If you visit our login page, we will set a temporary cookie to determine if your browser accepts cookies. This cookie contains no personal data and is discarded when you close your browser.</p><p>When you log in, we will also set up several cookies to save your login information and your screen display choices. Login cookies last for two days, and screen options cookies last for a year. If you select &quot;Remember Me&quot;, your login will persist for two weeks. If you log out of your account, the login cookies will be removed.</p><p>If you edit or publish an article, an additional cookie will be saved in your browser. This cookie includes no personal data and simply indicates the post ID of the article you just edited. It expires after 1 day.</p><h2>Embedded content from other websites</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Articles on this site may include embedded content (e.g. videos, images, articles, etc.). Embedded content from other websites behaves in the exact same way as if the visitor has visited the other website.</p><p>These websites may collect data about you, use cookies, embed additional third-party tracking, and monitor your interaction with that embedded content, including tracking your interaction with the embedded content if you have an account and are logged in to that website.</p><h2>Who we share your data with</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you request a password reset, your IP address will be included in the reset email.</p><h2>How long we retain your data</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you leave a comment, the comment and its metadata are retained indefinitely. This is so we can recognize and approve any follow-up comments automatically instead of holding them in a moderation queue.</p><p>For users that register on our website (if any), we also store the personal information they provide in their user profile. All users can see, edit, or delete their personal information at any time (except they cannot change their username). Website administrators can also see and edit that information.</p><h2>What rights you have over your data</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>If you have an account on this site, or have left comments, you can request to receive an exported file of the personal data we hold about you, including any data you have provided to us. You can also request that we erase any personal data we hold about you. This does not include any data we are obliged to keep for administrative, legal, or security purposes.</p><h2>Where we send your data</h2><p><strong class="privacy-policy-tutorial">Suggested text: </strong>Visitor comments may be checked through an automated spam detection service.</p>',
    slug: "privacy",
  },
];

export const userTypes: string[] = [
  "member",
  "council",
  "speaker",
  "ambassador",
  "minister",
];

export const userTypesProps: UserTypeProps[] = [
  { name: "member" } as UserTypeProps,
  { name: "council" } as UserTypeProps,
  { name: "speaker" } as UserTypeProps,
  { name: "ambassador" } as UserTypeProps,
  { name: "minister" } as UserTypeProps,
];

export const leaders: Leader[] = [
  {
    leaders: 5,
    pct: 67,
    status: "Minister",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "x",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Ambassador",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "8HDeNuCpyusuG7ObjzbdPzRyVhYC",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Speaker",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "z",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Council",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "k",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Minister",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "o",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Minister",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "x22",
  },
  {
    leaders: 5,
    pct: 67,
    status: "Minister",
    avatar: "https://picsum.photos/40/40",
    displayName: "Moshe",
    email: "moshe@gmail.com",
    score: 75,
    subscribers: 4,
    userId: "p",
  },
];

export const leader: Leader = {
  leaders: 5,
  pct: 67,
  status: "Minister",
  avatar: "https://picsum.photos/40/40",
  displayName: "Moshe",
  email: "moshe@gmail.com",
  score: 75,
  subscribers: 4,
  userId: "x",
};
export const timeframes: TimeFrame[] = [
  {
    index: 1,
    name: "1 hour",
    seconds: 1000 * 3600,
    chosen: true,
  },
  {
    index: 2,
    name: "2 hours",
    seconds: 2000 * 3600,
    chosen: true,
  },
  {
    index: 3,
    name: "3 hours",
    seconds: 2000 * 3600,
    chosen: true,
  },
];

export const coins: { [key: string]: Coin } = {
  CAKE: {
    symbol: "CAKE",
    price: 39.97549,
    name: "PancakeSwap",
    id: 4195,
    trend: -2.17,
  },
  BNB: {
    symbol: "BNB",
    price: 39.97549,
    name: "BNB",
    id: 4195,
    trend: -2.17,
  },
  FTT: {
    symbol: "FTT",
    price: 39.97549,
    name: "FTX Token",
    id: 4195,
    trend: -2.17,
  },
  HBAR: {
    symbol: "HBAR",
    price: 0.20472,
    name: "Hedera",
    id: 22,
    trend: -2.459,
  },
  SAND: {
    symbol: "SAND",
    name: "The Sandbox",
    id: 6210,
    price: 2.9493,
    trend: -1.909,
  },
  VET: {
    symbol: "VET",
    name: "VeChain",
    id: 23,
    trend: -1.795,
    price: 0.049516,
  },
  NEAR: {
    symbol: "NEAR",
    name: "NEAR Protocol",
    id: 14,
    trend: 0.475,
    price: 10.569,
  },
  UNI: {
    symbol: "UNI",
    name: "Uniswap",
    id: 7083,
    trend: -3.326,
    price: 8.72,
  },
  STX: {
    symbol: "STX",
    name: "Stacks",
    id: 35,
    trend: -2.632,
    price: 1.11,
  },
  BSV: {
    symbol: "BSV",
    name: "Bitcoin SV",
    id: 38,
    trend: -1.33,
    price: 79.95,
  },
  FIL: {
    symbol: "FIL",
    name: "Filecoin",
    id: 25,
    trend: -1.251,
    price: 18.87,
  },
  DAI: {
    symbol: "DAI",
    name: "Dai",
    id: 4943,
    trend: -0.001,
    price: 0.999775,
  },
  EGLD: {
    symbol: "EGLD",
    name: "Elrond",
    id: 29,
    trend: -1.314,
    price: 135.97,
  },
  AXS: {
    symbol: "AXS",
    name: "Axie Infinity",
    id: 6783,
    trend: -3.239,
    price: 50.19,
  },
  XMR: {
    symbol: "XMR",
    name: "Monero",
    id: 28,
    trend: 2.074,
    price: 169.34,
  },
  CRO: {
    symbol: "CRO",
    name: "Crypto.com Coin",
    id: 3635,
    trend: -1.514,
    price: 0.4033,
  },
  DOT: {
    symbol: "DOT",
    name: "Polkadot",
    id: 8,
    trend: -2.483,
    price: 16.89,
  },
  XTZ: {
    symbol: "XTZ",
    name: "Tezos",
    id: 30,
    trend: -3.185,
    price: 3.04,
  },
  ALGO: {
    symbol: "ALGO",
    name: "Algorand",
    id: 16,
    trend: -1.317,
    price: 0.7642,
  },
  AAVE: {
    symbol: "AAVE",
    name: "Aave",
    id: 7278,
    trend: -3.218,
    price: 120.6,
  },
  AVAX: {
    symbol: "AVAX",
    name: "Avalanche",
    id: 10,
    trend: -1.186,
    price: 75.8,
  },
  ETC: {
    symbol: "ETC",
    name: "Ethereum Classic",
    id: 26,
    trend: -2.048,
    price: 27.26,
  },
  XRP: {
    symbol: "XRP",
    name: "XRP",
    id: 6,
    trend: -2.085,
    price: 0.73875,
  },
  LTC: {
    symbol: "LTC",
    name: "Litecoin",
    id: 15,
    trend: -1.621,
    price: 103.2,
  },
  FTM: {
    symbol: "FTM",
    name: "Fantom",
    id: 17,
    trend: -14.892,
    price: 1.439,
  },
  MATIC: {
    symbol: "MATIC",
    name: "Polygon",
    id: 11,
    trend: -1.908,
    price: 1.4804,
  },
  MANA: {
    symbol: "MANA",
    name: "Decentraland",
    id: 1966,
    trend: -2.383,
    price: 2.499,
  },
  BCH: {
    symbol: "BCH",
    name: "Bitcoin Cash",
    id: 19,
    trend: -1.681,
    price: 289.52,
  },
  GRT: {
    symbol: "GRT",
    name: "The Graph",
    id: 6719,
    trend: -1.297,
    price: 0.3425,
  },
  SHIB: {
    symbol: "SHIB",
    name: "SHIBA INU",
    id: 5994,
    trend: -2.234,
    price: 0.00002407,
  },
  EOS: {
    symbol: "EOS",
    name: "EOS",
    id: 34,
    trend: -1.746,
    price: 2.0142,
  },
  DOGE: {
    symbol: "DOGE",
    name: "Dogecoin",
    id: 9,
    trend: -1.28,
    price: 0.1234,
  },
  ATOM: {
    symbol: "ATOM",
    name: "Cosmos",
    id: 12,
    trend: -5.575,
    price: 29.13,
  },
  BTC: {
    symbol: "BTC",
    name: "Bitcoin",
    id: 1,
    trend: -1.322,
    price: 38881.65,
  },
  SOL: {
    symbol: "SOL",
    name: "Solana",
    id: 5,
    trend: -2.042,
    price: 87.79,
  },
  WBTC: {
    symbol: "WBTC",
    name: "Wrapped Bitcoin",
    id: 3717,
    trend: -1.243,
    price: 38908.2,
  },
  XLM: {
    symbol: "XLM",
    name: "Stellar",
    id: 20,
    trend: -0.558,
    price: 0.179244,
  },
  ETH: {
    symbol: "ETH",
    name: "Ethereum",
    id: 2,
    trend: -0.997,
    price: 2639.37,
  },
  LINK: {
    symbol: "LINK",
    name: "Chainlink",
    id: 1975,
    trend: -2.189,
    price: 13.72,
  },
  TRX: {
    symbol: "TRX",
    name: "TRON",
    id: 18,
    trend: -1.11,
    price: 0.059767,
  },
  ADA: {
    symbol: "ADA",
    name: "Cardano",
    id: 4,
    trend: -2.204,
    price: 0.846327,
  },
  LUNA: {
    symbol: "LUNA",
    name: "Luna Coin",
    id: 674,
    trend: -3.03,
    price: 84.855,
  },
};

export const totals = {
  "BTC-ETH": {
    total: 10,
    success: 3,
  },
  SHIB: {
    total: 11,
    success: 10,
  },
  KDA: {
    total: 7,
    success: 5,
  },
  NEAR: {
    total: 11,
    success: 11,
  },
  HNT: {
    total: 18,
    success: 17,
  },
  COMP: {
    total: 2,
    success: 1,
  },
  BTC: {
    total: 10,
    success: 3,
  },
  "MATIC-SHIB": {
    total: 7,
    success: 3,
  },
  "REEF-FTM": {
    total: 3,
    success: 1,
  },
};

export const allPairs = [
  ["BTC", "ETH"],
  ["ADA", "SOL"],
  ["DOGE", "SHIB"],
  ["ETH", "BNB"],
  ["DOT", "MATIC"],
  ["XRP", "ADA"],
  ["LTC", "XRP"],
  ["CRO", "BNB"],
  ["SAND", "MANA"],
  ["UNI", "CAKE"],
  ["XLM", "XTZ"],
  ["LUNA", "DOGE"],
  ["DOGE", "BABYDOGE"],
  ["LINK", "TRON"],
  ["FTT", "BNB"],
];

export const allCoins = [
  "BTC",
  "ETH",
  "BNB",
  "ADA",
  "SOL",
  "XRP",
  "LUNA",
  "DOGE",
  "DOT",
  "AVAX",
  "SHIB",
  "MATIC",
  "ATOM",
  "WBTC",
  "DAI",
  "CRO",
  "LTC",
  "LINK",
  "NEAR",
  "UNI",
  "FTM",
  "ALGO",
  "TRX",
  "BCH",
  "FTT",
  "XLM",
  "MANA",
  "HBAR",
  "VET",
  "LEO",
  "ETC",
  "KLAY",
  "AXS",
  "EGLD",
  "FIL",
  "SAND",
  "XMR",
  "THETA",
  "HNT",
  "XTZ",
  "MIOTA",
  "ONE",
  "EOS",
  "AAVE",
  "CAKE",
  "GRT",
  "BTT",
  "BABYDOGE",
  "BSV",
  "STX",
];

export const user = {
  uid: "8HDeNuCpyusuG7ObjzbdPzRyVhYC",
  email: "avi111@gmail.com",
  emailVerified: true,
  isAnonymous: false,
  providerData: [
    {
      providerId: "google.com",
      uid: "0891826412618452482876655656109387851822",
      displayName: null,
      email: "avi111@gmail.com",
      phoneNumber: null,
      photoURL: null,
    },
  ],
  stsTokenManager: {
    refreshToken:
      "Dlw1AXk80PEufziYLIMCNFofUI49C_qz1KAsLCKBcJn4dqmlT9wrPAJ006cBajzgno9m4s45qDxI0Gh-NxwLyk_dPMx1qiKnBx2U3uN8buC3BM1rKpsttURVEqBnUTcIuX5MtqKZLz3dSKM7rulYeKVTl9Gy8kmf5nCLueAwKhIPVXqJpUV5jCIVoehYz7ETErJs-AVob0II",
    accessToken:
      "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6ImF2aTExMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXV0aF90aW1lIjoxNjQ2MDc0NTkxLCJ1c2VyX2lkIjoiOEhEZU51Q3B5dXN1RzdPYmp6YmRQelJ5VmhZQyIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYXZpMTExQGdtYWlsLmNvbSJdLCJnb29nbGUuY29tIjpbIjA4OTE4MjY0MTI2MTg0NTI0ODI4NzY2NTU2NTYxMDkzODc4NTE4MjIiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn0sImlhdCI6MTY0NjA3NDU5MSwiZXhwIjoxNjQ2MDc4MTkxLCJhdWQiOiJjb2lucGFybGlhbWVudC01MWFlMSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9jb2lucGFybGlhbWVudC01MWFlMSIsInN1YiI6IjhIRGVOdUNweXVzdUc3T2JqemJkUHpSeVZoWUMifQ.",
    expirationTime: 1646078191542,
  },
  createdAt: "1640039394107",
  lastLoginAt: "1646074591537",
  apiKey: "AIzaSyDZvpoggvWLqqr-QUhOxOyq4n5aaoiWMXk",
  appName: "[DEFAULT]",
} as unknown as User;

export const userInfo = {
  favorites: ["NEAR"],
  country: "",
  lastName: "",
  leader: ["8HDeNuCpyusuG7ObjzbdPzRyVhYC"],
  address: "",
  displayName: "mushon",
  subscribers: ["8HDeNuCpyusuG7ObjzbdPzRyVhYC"],
  mfa: false,
  admin: true,
  token:
    "cWHlYVrY35Q8J23H7p59fW:APA91bFYQlJyctdJHjVfeY_9FpDDzw4-8Knnl64lCumsBDcX6FoFCFpkam4QJwlV24Nz-syGE7_YmhHoqOVySCljYmHZbcFUMwmlAR5wl0qs_eTWRbRmTCFK1VpVro4JNXaTNVwcVhPT",
  firstName: "",
  children: [],
  lang: "english",
  email: "avi111@gmail.com",
  status: {
    color: Colors.SILVER,
    givenCPM: 1,
    index: 0,
    weight: 1,
    name: "Member",
    share: 50,
  },
  voteStatistics: {
    score: 53,
    total: 62,
    rank: 0,
    commission: 0,
    successful: 50,
    pax: 53,
  },
};
