export const texts = {
  continueWith: "continue with",
  facebook: "facebook",
  google: "google",
  twitter: "twitter",
  noAccount: "don't have an account?",
  haveAccount: "already have an account?",
  login: "login",
  continue: "continue",
  firstTimeLoginModalTitle: "Do you want to continue?",
  firstTimeLoginModalText:
    "Notice that once you choose a username, you can't change it again. Are you sure you want {username} as a username?",
  signUp: "signup",
  agree: "I agree to {terms & conditions} of the site",
  termsConditions: "terms & conditions",
  email: "email",
  password: "password",
  confirmPassword: "confirm password",
  username: "username",
  generate: "generate",
  chooseUserName: "choose username",
  chooseUserNameText:
    "Your username is how other community members will see you.",
  FoundationSelect:'For every vote you cast, CP will match it and donate to one of The following foundations',
  ForgetPasswordText:`Don't remember password ?`,
  UserNameValidation: 'User name should be unique and between 8 to 15 characters.',
  Total100: 'total share must be 100%',
  UserInfoUpdate:"user info was updated",
  UserFailUpdate: "user failed to be updated",
  success: "success",
  failed: "failed",
  PasswordResetLinkSent: "Password reset link has been sent to your email.",
  AgreetNc : "You must agree to t&c",
  PasswordUpdatSuccess: "Password updated successfully.",
  PasswordMustContain: "Password must contain at least 1 capital letter(s) (ABCDEFGHIJKLMNOPQRSTUVWXYZ). It must contain at least 1 numeric character(s) (0123456789). It must not contain more than 3 identical consecutive characters (AAA, iiii, $$$$$ ...). It must not contain your user name.",
  FASecurityAdded: "2FA security added to your account.",
  WrongCode: "Wrong code please try again.",
  CopiedClipboard: "copied to clipboard.",
  FeatureAvailableSoon: "Feature will be available soon",
};

export const urls = {
  termsConditions: "/terms-conditions",
};
