import { filterCoins } from "./Coin";
import { difference } from "lodash";

describe("coins", () => {
  it("filters coin", () => {
    const coins = {
      REEF: {
        price: 0.0087103,
        symbol: "REEF",
        id: 78,
        name: "Reef",
      },
      FTM: {
        price: 2.0745,
        symbol: "FTM",
        id: 17,
        name: "Fantom",
      },
      MATIC: {
        price: 1.6694,
        symbol: "MATIC",
        id: 11,
        name: "Polygon",
      },
      KSM: {
        price: 178.2,
        symbol: "KSM",
        id: 37,
        name: "Kusama",
      },
      BTC: {
        price: 40602.72,
        symbol: "BTC",
        id: 1,
        name: "Bitcoin",
      },
      SC: {
        price: 0.01103,
        symbol: "SC",
        id: 63,
        name: "Siacoin",
      },
      STX: {
        price: 1.52,
        symbol: "STX",
        id: 35,
        name: "Stacks",
      },
      ATOM: {
        price: 30.78,
        symbol: "ATOM",
        id: 12,
        name: "Cosmos",
      },
      COTI: {
        price: 0.3029,
        symbol: "COTI",
        id: 73,
        name: "COTI",
      },
      ETP: {
        price: 0.1258,
        symbol: "ETP",
        id: 220,
        name: "Metaverse ETP",
      },
      ROSE: {
        price: 0.35093,
        symbol: "ROSE",
        id: 43,
        name: "Oasis Network",
      },
      GRT: {
        price: 0.4335,
        symbol: "GRT",
        id: 6719,
        name: "The Graph",
      },
      QNT: {
        price: 132.5,
        symbol: "QNT",
        id: 3155,
        name: "Quant",
      },
      LPT: {
        price: 29.01,
        symbol: "LPT",
        id: 3640,
        name: "Livepeer",
      },
      NEXO: {
        price: 2.2036,
        symbol: "NEXO",
        id: 2694,
        name: "Nexo",
      },
      DOT: {
        price: 20.12,
        symbol: "DOT",
        id: 8,
        name: "Polkadot",
      },
      BSV: {
        price: 93.922,
        symbol: "BSV",
        id: 38,
        name: "Bitcoin SV",
      },
      ZIL: {
        price: 0.049323,
        symbol: "ZIL",
        id: 56,
        name: "Zilliqa",
      },
      LTC: {
        price: 119.12,
        symbol: "LTC",
        id: 15,
        name: "Litecoin",
      },
      XTZ: {
        price: 3.96,
        symbol: "XTZ",
        id: 30,
        name: "Tezos",
      },
      SOL: {
        price: 110.75,
        symbol: "SOL",
        id: 5,
        name: "Solana",
      },
      MANA: {
        price: 2.747,
        symbol: "MANA",
        id: 1966,
        name: "Decentraland",
      },
      XLM: {
        price: 0.206889,
        symbol: "XLM",
        id: 20,
        name: "Stellar",
      },
      CRO: {
        price: 0.4305,
        symbol: "CRO",
        id: 3635,
        name: "Crypto.com Coin",
      },
      LRC: {
        price: 0.8999,
        symbol: "LRC",
        id: 1934,
        name: "Loopring",
      },
      MOB: {
        price: 4.7872,
        symbol: "MOB",
        id: 89,
        name: "MobileCoin",
      },
      VET: {
        price: 0.057518,
        symbol: "VET",
        id: 23,
        name: "VeChain",
      },
      XSN: {
        price: 0.067649,
        symbol: "XSN",
        id: 226,
        name: "Stakenet",
      },
      ETH: {
        price: 2953.17,
        symbol: "ETH",
        id: 2,
        name: "Ethereum",
      },
      LINK: {
        price: 17.11,
        symbol: "LINK",
        id: 1975,
        name: "Chainlink",
      },
      DGB: {
        price: 0.022544,
        symbol: "DGB",
        id: 70,
        name: "DigiByte",
      },
      NEO: {
        price: 22.291,
        symbol: "NEO",
        id: 41,
        name: "Neo",
      },
      AVAX: {
        price: 76.25,
        symbol: "AVAX",
        id: 10,
        name: "Avalanche",
      },
      XRA: {
        price: 0.015763,
        symbol: "XRA",
        id: 591,
        name: "Ratecoin",
      },
      WBTC: {
        price: 40629.9,
        symbol: "WBTC",
        id: 3717,
        name: "Wrapped Bitcoin",
      },
      SRM: {
        price: 2.391,
        symbol: "SRM",
        id: 72,
        name: "Serum",
      },
      QTUM: {
        price: 6.75294,
        symbol: "QTUM",
        id: 58,
        name: "Qtum",
      },
      MASK: {
        price: 6.46,
        symbol: "MASK",
        id: 429,
        name: "NFTX Hashmasks Index",
      },
      USDC: {
        price: 0.9994,
        symbol: "USDC",
        id: 3408,
        name: "USD Coin",
      },
      XMR: {
        price: 160.79,
        symbol: "XMR",
        id: 28,
        name: "Monero",
      },
      DASH: {
        price: 101.2,
        symbol: "DASH",
        id: 46,
        name: "Dash",
      },
      AMP: {
        price: 0.03079,
        symbol: "AMP",
        id: 6945,
        name: "Amp",
      },
      CHZ: {
        price: 0.1975,
        symbol: "CHZ",
        id: 4066,
        name: "Chiliz",
      },
      ZEN: {
        price: 41.89,
        symbol: "ZEN",
        id: 64,
        name: "Horizen",
      },
      FIL: {
        price: 21.36,
        symbol: "FIL",
        id: 25,
        name: "Filecoin",
      },
      UST: {
        price: 1.0008,
        symbol: "UST",
        id: 13,
        name: "TerraUSD",
      },
      AAVE: {
        price: 163.29,
        symbol: "AAVE",
        id: 7278,
        name: "Aave",
      },
      ENJ: {
        price: 1.81,
        symbol: "ENJ",
        id: 2130,
        name: "Enjin Coin",
      },
      CRV: {
        price: 3.35,
        symbol: "CRV",
        id: 6538,
        name: "Curve DAO Token",
      },
      XRD: {
        price: 0.17005,
        symbol: "XRD",
        id: 782,
        name: "Radix",
      },
      XVG: {
        price: 0.010674,
        symbol: "XVG",
        id: 82,
        name: "Verge",
      },
      ZEC: {
        price: 105.92,
        symbol: "ZEC",
        id: 40,
        name: "Zcash",
      },
      LSK: {
        price: 1.76232,
        symbol: "LSK",
        id: 76,
        name: "Lisk",
      },
      GALA: {
        price: 0.19894,
        symbol: "GALA",
        id: 7080,
        name: "Gala",
      },
      BCH: {
        price: 299.46,
        symbol: "BCH",
        id: 19,
        name: "Bitcoin Cash",
      },
      LUNA: {
        price: 52.016,
        symbol: "LUNA",
        id: 674,
        name: "Luna Coin",
      },
      NEAR: {
        price: 12.709,
        symbol: "NEAR",
        id: 14,
        name: "NEAR Protocol",
      },
      SHIB: {
        price: 0.00002196,
        symbol: "SHIB",
        id: 5994,
        name: "SHIBA INU",
      },
      MKR: {
        price: 2269.52,
        symbol: "MKR",
        id: 1518,
        name: "Maker",
      },
      CTK: {
        price: 1.435,
        symbol: "CTK",
        id: 129,
        name: "CertiK",
      },
      ADA: {
        price: 1.1108,
        symbol: "ADA",
        id: 4,
        name: "Cardano",
      },
      NKN: {
        price: 0.2188,
        symbol: "NKN",
        id: 102,
        name: "NKN",
      },
      DAI: {
        price: 0.999999,
        symbol: "DAI",
        id: 4943,
        name: "Dai",
      },
      ICX: {
        price: 0.804,
        symbol: "ICX",
        id: 62,
        name: "ICON",
      },
      UNI: {
        price: 11,
        symbol: "UNI",
        id: 7083,
        name: "Uniswap",
      },
      XDC: {
        price: 0.0599,
        symbol: "XDC",
        id: 52,
        name: "XDC Network",
      },
      DOGE: {
        price: 0.1452,
        symbol: "DOGE",
        id: 9,
        name: "Dogecoin",
      },
      IOTX: {
        price: 0.09111,
        symbol: "IOTX",
        id: 53,
        name: "IoTeX",
      },
      EOS: {
        price: 2.44,
        symbol: "EOS",
        id: 34,
        name: "EOS",
      },
      XRP: {
        price: 0.63746,
        symbol: "XRP",
        id: 6,
        name: "XRP",
      },
      ICP: {
        price: 21.73,
        symbol: "ICP",
        id: 21,
        name: "Internet Computer",
      },
      ANKR: {
        price: 0.08065,
        symbol: "ANKR",
        id: 3783,
        name: "Ankr",
      },
      AXS: {
        price: 50.41,
        symbol: "AXS",
        id: 6783,
        name: "Axie Infinity",
      },
      OMG: {
        price: 4.92,
        symbol: "OMG",
        id: 1808,
        name: "OMG Network",
      },
      EGLD: {
        price: 150.35,
        symbol: "EGLD",
        id: 29,
        name: "Elrond",
      },
      CLO: {
        price: 0.0051259,
        symbol: "CLO",
        id: 208,
        name: "Callisto Network",
      },
      ETC: {
        price: 29.01,
        symbol: "ETC",
        id: 26,
        name: "Ethereum Classic",
      },
      BOBA: {
        price: 1.647,
        symbol: "BOBA",
        id: 92,
        name: "Boba Network",
      },
      COMP: {
        price: 132.83,
        symbol: "COMP",
        id: 724,
        name: "Compound Coin",
      },
      WAVES: {
        price: 9.1996,
        symbol: "WAVES",
        id: 44,
        name: "Waves",
      },
      ALGO: {
        price: 0.9826,
        symbol: "ALGO",
        id: 16,
        name: "Algorand",
      },
      FTT: {
        price: 45.117,
        symbol: "FTT",
        id: 4195,
        name: "FTX Token",
      },
      TLOS: {
        price: 1.1812,
        symbol: "TLOS",
        id: 101,
        name: "Telos",
      },
      BTG: {
        price: 32.114,
        symbol: "BTG",
        id: 61,
        name: "Bitcoin Gold",
      },
      BAT: {
        price: 0.87721,
        symbol: "BAT",
        id: 1697,
        name: "Basic Attention Token",
      },
      TRX: {
        price: 0.063854,
        symbol: "TRX",
        id: 18,
        name: "TRON",
      },
    };

    const allcoins = [
      "BTC",
      "ETH",
      "BNB",
      "ADA",
      "SOL",
      "XRP",
      "LUNA",
      "DOGE",
      "DOT",
      "AVAX",
      "SHIB",
      "MATIC",
      "ATOM",
      "WBTC",
      "DAI",
      "CRO",
      "LTC",
      "LINK",
      "NEAR",
      "UNI",
      "FTM",
      "ALGO",
      "TRX",
      "BCH",
      "FTT",
      "XLM",
      "MANA",
      "HBAR",
      "VET",
      "LEO",
      "ETC",
      "KLAY",
      "AXS",
      "EGLD",
      "FIL",
      "SAND",
      "XMR",
      "THETA",
      "HNT",
      "XTZ",
      "MIOTA",
      "ONE",
      "EOS",
      "AAVE",
      "CAKE",
      "GRT",
      "BTT",
      "BABYDOGE",
      "BSV",
      "STX",
    ];

    const actual = filterCoins(coins, allcoins);
    const diff = difference(Object.keys(actual), allcoins);
    expect(diff.length).toBe(0);
  });
});
